# ./docker-compose.yml

version: '3'

services:
    apmc:
        container_name: mc
        stdin_open: true
        tty: true
        restart: always
        build: .
        volumes:
            - ./Minecraft:/home/Minecraft
        ports:
            - "25565:25565"
        environment: 
            - minram: 4G
            - maxram: 8G
            - server_type: paper
            - TZ: America/Chicago