#!/usr/bin/env bash

for pid in $(pgrep -f backup-server); do
    if [ $pid != $$ ]; then
        printf "[$(date)] : backup-server : Process is already running with PID $pid"
        exit 1
    fi
done

while :
do
	sleep 60
done