#!/usr/bin/env bash

# flock command that locks the script for only a single instance
[ "${FLOCKER}"  != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

mkdir -p "$dir/Backups"


# Ensure that saving happens even if script is interupted.
trap cleanup INT
function cleanup {
	send-2-screen mc "say Server backup complete."
	send-2-screen mc "save-on"
	send-2-screen mc "save-all"
}

send-2-screen mc "save-all"
send-2-screen mc "say Server backup in progress."
send-2-screen mc "save-off"

date=$(date +%Y-%m-%d)

mkdir -p "$dir/Backups/$date"
filename="${date}_$(date +%H.%M)_mc-server"

tar --exclude="$dir/Backups" -zcvf "$dir/Backups/$date/$filename.tgz" "$dir"

cleanup

exit 0