#!/usr/bin/env bash

# A simple script to verify if an instance of a given script is already running
# Purpose: provide a mechanism to protect against multiple script instances

function message {
    printf "Error: missing arguments. please include <script-name> <current-script-ID>\n"
}

if [ -z "$1" ] || [[ ! "$2" =~ ^[0-9]+$ ]] || [ $# != 2 ]
then
    message
    exit 1
fi

process_name=$1
process_id=$2

for pid in $(pgrep -f $process_name); do
    if [ $pid != $process_id ] && [ $pid != $$ ] && [ $pid != $PPID ]; then
        printf "[$(date)] : $process_name : Process is already running with PID $pid\n"
        exit 1
    fi
done

exit 0