#!/usr/bin/env bash

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

# Creates script for starting server
printf "#!/usr/bin/env bash\nstart-server" > $dir/start.sh
chmod +x $dir/start.sh

update-server -no
start-server

# trap "/home/Minecraft/send-2-screen.sh mc stop" SIGTERM SIGINT
# trap touch /home/Minecraft/testing.txt SIGTERM SIGINT

# Keeps docker container alive
while :
do
	sleep 60
done

exit 0
