#!/usr/bin/env bash

# flock command that locks the script for only a single instance
[ "${FLOCKER}"  != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

crond -l 0 -L /var/log/cron.log

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

# If the user has indicated a crontab pattern, add that to the crontable
if [ ! -z "$backup_cron" ]; then
# Remove leading and trailing whitespace
	backup_cron=$(printf "$backup_cron" | awk '{$1=$1}1')
	( crontab -u root -l; printf "$backup_cron backup-server\n" ) | crontab -u root -
fi


# Creates script for starting server
printf "#!/usr/bin/env bash\nstart-server" > $dir/start.sh
chmod +x $dir/start.sh

upgrade-server -no
start-server

# trap "/home/Minecraft/send-2-screen.sh mc stop" SIGTERM SIGINT
# trap touch /home/Minecraft/testing.txt SIGTERM SIGINT

# Keeps docker container alive - possibly add in the auto-restart script detector in place of the wait
while :
do
	sleep 60
done

exit 0
