#!/usr/bin/env bash

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

if [ ! -z "$minram" ]; then
    xms="-Xms"$minram
fi
if [ ! -z "$maxram" ]; then
    xmx="-Xmx"$maxram
fi
if [ -z "$start_script" ]; then 
    start_script="java $xmx $xms -jar $dir/*server.jar nogui"
fi

stop -q
sleep 5

send-2-screen mc "cd $dir; $start_script"
sleep 5

while true;
do 
    sleep 1
    if [ ! grep -q "eula=true" $dir/eula.txt ]; then
        if [ "$EULA" = true ]; then
            sed -i 's/eula=false/eula=true/' $dir/eula.txt
        fi
    else
        send-2-screen mc "cd $dir; $start_script"
        break
    fi
done

exit 0