#!/usr/bin/env bash

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

if [ ! -z "$minram" ]; then
    xms="-Xms"$minram
fi
if [ ! -z "$maxram" ]; then
    xmx="-Xmx"$maxram
fi
if [ -z "$start_script" ]; then 
    start_script="java $xmx $xms -jar $dir/*server.jar nogui"
fi

stop-server -q
sleep 5

function run_server {
    while ! grep -q "eula=true" $dir/eula.txt;
    do 
        sleep 1
        if [ "$EULA" = true ]; then
            sed -i 's/eula=false/eula=true/' $dir/eula.txt
        fi
    done
    send-2-screen mc "cd $dir; $start_script"
}

if [ -f "$dir/eula.txt" ]; then
    run_server
else
    send-2-screen mc "cd $dir; $start_script"
    sleep 10
    run_server
fi



exit 0