#!/usr/bin/env bash

check-script stop-server $$ || exit 1

quiet=false

OPTIND=1
while getopts "q" opt; do
	case $opt in 
	q)
		quiet=true;;
	n)
		restart_server=false;;
	esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift

if [ "$quiet" = false ]; then
    for i in {1..10}
    do
        sleep 1
        t=$(expr 10 - $i)
        send-2-screen mc "say Server shutting down in $t seconds!"
    done
fi

# Only stop if server is running
if [ $(server-status) = "running" ]; then
    send-2-screen mc "stop"
    exit 0
fi

exit 1