#!/usr/bin/env bash

quiet=false
restart_server=true

OPTIND=1
while getopts "qn" opt; do
	case $opt in 
	q)
		quiet=true;;
	n)
		restart_server=false;;
	esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift


sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

mkdir -p $dir/server-versions
mv *.jar $dir/server-versions

function paper {
	send-2-screen build "get-latest-paper"
}

function spigot {
	find $dir -type f -iname "*.sh" -or -iname "*.jar" -exec chmod +x {} \;
	if [ ! -f $dir/*spigot-server.jar ]; then
		git config --global --unset core.autocrlf
		send-2-screen build "build-latest-server"
	fi
}

if [ `echo $server_type | tr [:upper:] [:lower:]` =  `echo spigot | tr [:upper:] [:lower:]` ]; then
	spigot
elif [ `echo $server_type | tr [:upper:] [:lower:]` =  `echo paper | tr [:upper:] [:lower:]` ]; then
	paper
else
	spigot
fi

if [ "$restart_server" = true ]; then

	if [ "$quiet" = true ]; then
		restart -q
	else
		restart
	fi
fi

exit 0
