#!/usr/bin/env bash

# flock command that locks the script for only a single instance
[ "${FLOCKER}"  != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

quiet=false
restart_server=true
override=false

OPTIND=1
while getopts "qno" opt; do
	case $opt in 
	q)
		quiet=true;;
	n)
		restart_server=false;;
	o) 
		override=true;;
	esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift


sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
dir="/home/Minecraft"

mkdir -p "$dir/server-versions"
mv "$dir/"*.jar "$dir/server-versions"

function paper {
	get-latest-paper
}

function spigot {
	find $dir -type f -iname "*.sh" -or -iname "*.jar" -exec chmod +x {} \;
	if [ ! -f $dir/*spigot-server.jar ]; then
		git config --global --unset core.autocrlf
		build-latest-server
	fi
}

function check_server {
	if [ `echo $server_type | tr [:upper:] [:lower:]` =  `echo spigot | tr [:upper:] [:lower:]` ]; then
		spigot
	elif [ `echo $server_type | tr [:upper:] [:lower:]` =  `echo paper | tr [:upper:] [:lower:]` ]; then
		paper
	else
		spigot
	fi
}

if [ "$override" = true ]; then 
	ls $dir/*server.jar  >/dev/null || check_server
	exit 0
fi
check_server



if [ "$restart_server" = true ]; then

	if [ "$quiet" = true ]; then
		restart-server -q
	else
		restart-server
	fi
fi

exit 0
